### ISSUE TITLE
bison-native-3.0.4-r0 - compile failed

### ISSUE THREAD

**Issue by dk-relpol** [karo-electronics/meta-karo-nxp#1]
Hi,

I'm trying to build an image for the tx6s-8134 board , meta-karo-nxp rev: 4.14.98-2.2.0-sumo . When building according to the instructions: [https://karo-electronics.github.io/docs/yocto-guide/yocto-sumo-guide/BuildTX6.html](url), throws the error:
ERROR: bison-native-3.0.4-r0 do_compile: oe_runmake failed
ERROR: bison-native-3.0.4-r0 do_compile: Function failed: do_compile (log file is located at / home / armsdk / KARO / YOCTO / karo / build-tx6s / tmp / work / x86_64-linux / bison-native / 3.0.4-r0 / temp / log.do_compile.112188)
ERROR: Logfile of failure stored in: /home/armsdk/KARO/YOCTO/karo/build-tx6s/tmp/work/x86_64-linux/bison-native/3.0.4-r0/temp/log.do_compile.112188

I find patch to yocto-poky: [https://marc.info/?l=openembedded-core&m=154715365203505&q=p4](url) .  More info: [https://marc.info/?l=openembedded-core&m=154715365203505&w=2](url)

This is a problem with YOCTO-poky, maybe you could add this information to README

**Comment by dk-relpol** [comment]
Build Configuration:
BB_VERSION           = "1.38.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "debian"
TARGET_SYS           = "arm-poky-linux-gnueabi"
MACHINE              = "tx6s-8134"
DISTRO               = "fsl-imx-xwayland"
DISTRO_VERSION       = "4.14-sumo"
TUNE_FEATURES        = "arm armv7a vfp neon callconvention-hard cortexa9"
TARGET_FPU           = "hard"
meta                 
meta-poky            = "HEAD:5ddf7fff992b065ee512878d2fe65f3e35d818cf"
meta-oe              
meta-multimedia      = "HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f"
meta-freescale       = "HEAD:86772601e7f6ea188dfaf64097edafc05e15aef3"
meta-freescale-3rdparty = "HEAD:82037216280a39957fb4272581637abec734ad50"
meta-freescale-distro = "HEAD:f7e2216e93aff14ac32728a13637a48df436b7f4"
meta-bsp             
meta-sdk             = "HEAD:c2602efbe743dbe5e7907646694d772144b56b2d"
meta-browser         = "HEAD:75640e14e325479c076b6272b646be7a239c18aa"
meta-gnome           
meta-networking      
meta-python          
meta-filesystems     = "HEAD:8760facba1bceb299b3613b8955621ddaa3d4c3f"
meta-qt5             = "HEAD:d4e7f73d04e8448d326b6f89908701e304e37d65"
meta-karo-nxp        = "HEAD:b05127a65b822d28d54f997e43975f7b8a0a5a2a"

**Comment by lw-karo** [comment]
see  #2
