### ISSUE TITLE
Where to search for imx-seco.inc, missing LAYERDEPENDS?

### ISSUE THREAD

**Issue by luzik** [karo-electronics/meta-karo-nxp#5]
meta-karo-nxp/recipes-bsp/imx-mkimage/imx-boot_1.0.bb
requires recipes-bsp/imx-seco/imx-seco.inc

but I can't find this file in any of
LAYERDEPENDS_karo-nxp

**Comment by theonlymb** [comment]
Yes this might miss.
But this does not break the build when you checked out the full bsp like described in documentation.

What are you trying to achieve?

**Comment by luzik** [comment]
Yes this is true. I have custom set of layers without karo-nxp-bsp. Found it in meta-imx
