### ISSUE TITLE
CONFIG_USB_EHCI_MXC

### ISSUE THREAD

**Issue by luzik** [karo-electronics/meta-karo-nxp#7]
I found that 5.15.32 do not have CONFIG_USB_EHCI_MXC option and you set it in mx8mm_defconfig
Did you mean CONFIG_USB_EHCI_FSL ?

**Comment by lw-karo** [comment]
luzik ***@***.***> wrote:

> I found that 5.15.32 do not have CONFIG_USB_EHCI_MXC option and you set it in mx8mm_defconfig
>
The CONFIG variable belongs to an obsolete driver which has been
removed from the kernel:
commit e7018751d2e603381ae6028ba4dd21ec45ce38bb
Author: Fabio Estevam ***@***.***>
Date:   Fri Nov 13 14:12:31 2020 -0300

    usb: host: ehci-mxc: Remove the driver
    
    The ehci-mxc driver was only used by i.MX non-DT platforms.
    
    Since 5.10-rc1, i.MX has been converted to a DT-only platform and all
    board files are gone.
    
    Remove the ehci-mxc driver as there are no more users at all.

> Did you mean CONFIG_USB_EHCI_FSL ?
> 
No.

What is your actual problem?


Lothar Waßmann
-- 
___________________________________________________________

Ka-Ro electronics GmbH | Pascalstraße 22 | D - 52076 Aachen
Phone: +49 2408 1402-0 | Fax: +49 2408 1402-10
Geschäftsführer: Matthias Kaussen
Handelsregistereintrag: Amtsgericht Aachen, HRB 4996

www.karo-electronics.de | ***@***.***
___________________________________________________________

**Comment by luzik** [comment]
No problem at all, just small notice, for keeping things clear without outdated lines
